BukminPanelBundle_homepage:
    pattern:  /
    defaults: { _controller: BukminPanelBundle:Default:index }
BukminPanelBundle_player:
    resource: "@BukminPanelBundle/Resources/config/routing/player.yml"
    prefix:   /player
BukminPanelBundle_ban:
    resource: "@BukminPanelBundle/Resources/config/routing/ban.yml"
    prefix:   /ban