parameters:
#    bukmin_panel.example.class: Bukmin\PanelBundle\Example

services:
#    bukmin_panel.example:
#        class: %bukmin_panel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
