<?php

namespace Bukmin\PanelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanRepository extends EntityRepository
{
}